### ISSUE TITLE
[NOTIFIER] Notifications séparées pour when_present

### ISSUE THREAD

**Issue by swann05** [jlpouffier/appdeamon-apps#2]
Salut, 
J'utilise ton Notifier depuis ta vidéo sur YouTube. Il rend bien service, merci pour ton travail.
J'ai cependant un problème avec when_present. Je n'arrive pas à savoir si c'est nouveau ou si cela a toujours été comme ça.
Par exemple, si j'arrive à la maison et que le lave-linge a tourné j'ai une notification. Mais si je ne vois pas la notification tout de suite ou si je n'ai pas le temps de le vider, ma compagne qui arrive juste après ne reçoit pas de notification à son tour.
J'ai essayé de modifier le code moi-même mais je suis bloqué n'ayant aucune connaissance en programmation, j'ai tenté par logique ...

**Comment by swann05** [comment]
`class notifier(hass.Hass): 
    def initialize(self):
        # Listen to all NOTIFIER events
        self.listen_event(self.callback_notifier_event_received , "NOTIFIER")
        self.listen_event(self.callback_notifier_discard_event_received , "NOTIFIER_DISCARD")
        self.listen_event(self.callback_button_clicked, "mobile_app_notification_action")
        self.listen_event(self.callback_notification_cleared, "mobile_app_notification_cleared")
        
        # Staged notification 1

        self.staged_notifications_1 = []
        self.listen_state(self.callback_home_occupied_1 , self.args["number_person"] , old = "0" , new = "1")
        self.listen_state(self.callback_home_occupied_1 , self.args["number_person"] , old = "0" , new = "2")

        # Staged notification 2

        self.staged_notifications_2 = []
        self.listen_state(self.callback_home_occupied_2 , self.args["number_person"] , old = "1" , new = "2")
        self.listen_state(self.callback_home_occupied_2 , self.args["number_person"] , old = "0" , new = "2")

        # Unoccupied

        self.listen_state(self.callback_home_unoccupied , self.args["number_person"] , old = "1" , new = "0")

        # Temporary watchers
        self.watchers_handles = []

        # log
        self.log("Initialized") 

    def callback_notifier_event_received(self, event_name, data, kwargs):
        self.log("NOTIFIER event received")  
        if "action" in data:
            action = data["action"]
            for person in self.args["persons"]:
                if action == "send_to_" + person["name"]:
                    self.send_to_person(data, person)
            if action == "send_to_all":
                #send_to_all
                self.send_to_all(data)
            if action == "send_to_present":
                #send_to_present
                self.send_to_present(data)
            if action == "send_to_absent":
                #send_to_absent
                self.send_to_absent(data)
            if action == "send_to_nearest":
                #send_to_nearest
                self.send_to_nearest(data)
            if action == "send_when_present":
                #send_when_present
                self.send_when_present(data) 
        
        if "persistent" in data:
            if data["persistent"]:
                self.log("Persisting the notification on Home Assistant Front-end ...")
                self.call_service("notify/persistent_notification", title = data["title"], message = data["message"])
        
        if "until" in data and 'tag' in data:
            until = data["until"]
            for watcher in until:
                watcher_handle = {}
                watcher_handle["id"] = self.listen_state(self.callback_until_watcher, watcher["entity_id"], new = str(watcher["new_state"]), oneshot = True, tag = data["tag"])
                watcher_handle["tag"] = data["tag"]
                self.watchers_handles.append(watcher_handle)
                self.log("All notifications with tag " + data["tag"] + " will be cleared if " + watcher["entity_id"] + " transitions to " + str(watcher["new_state"]))

    def callback_notifier_discard_event_received(self, event_name, data, kwargs):
        self.clear_notifications(data["tag"])

    def callback_until_watcher(self, entity, attribute, old, new, kwargs):
        self.clear_notifications(kwargs["tag"])

    def callback_button_clicked(self, event_name, data, kwargs):
        if "tag" in data:
            self.clear_notifications(data["tag"])

    def callback_notification_cleared(self, event_name, data, kwargs):
        if "tag" in data:
            self.clear_notifications(data["tag"])
    
    def clear_notifications(self, tag):
        self.log("Clearing notifications with tag " + tag + " (if any) ...")
        notification_data = {}
        notification_data["tag"] = tag
        for person in self.args["persons"]:
            self.call_service(person["notification_service"], message = "clear_notification", data = notification_data)
        self.cancel_watchers(tag)
        self.staged_notifications_2.clear()

    def cancel_watchers(self, tag):
        self.log("Removing watchers with tag " + tag + " (if any) ...")
        for watcher in list(self.watchers_handles):
            if watcher["tag"] == tag:
                self.watchers_handles.remove(watcher)
        
    def build_notification_data(self, data):
        notification_data = {}
        if "callback" in data:
            notification_data["actions"] = []
            for callback in data["callback"]:
                action = {
                    "action":callback["event"],
                    "title":callback["title"]
                }
                notification_data["actions"].append(action)
        if "timeout" in data:
            notification_data["timeout"] = data["timeout"]
        if "click_url" in data:
            notification_data["clickAction"] = data["click_url"]
        if "image_url" in data:
            notification_data["image"] = data["image_url"]
        if "icon" in data:
            notification_data["notification_icon"] = data["icon"]
        if "color" in data:
            notification_data["color"] = data["color"]
        if "tag" in data:
            notification_data["tag"] = data["tag"]
        return notification_data

    def send_to_person(self, data, person):
        self.log("Sending notification to " + person["name"])
        notification_data = self.build_notification_data(data)
        self.call_service(person["notification_service"], title = data["title"], message = data["message"], data = notification_data)

    def send_to_all(self, data):
        for person in self.args["persons"]:
            self.send_to_person(data, person)

    def send_to_present(self, data):
        for person in self.args["persons"]:
            if self.get_state(person["id"]) == "home" or float(self.get_state(person["proximity_id"])) <= self.args["proximity_threshold"]:
                self.send_to_person(data, person)
                
    def send_to_absent(self, data):
        for person in self.args["persons"]:
            if self.get_state(person["id"]) != "home" or float(self.get_state(person["proximity_id"])) > self.args["proximity_threshold"]:
                self.send_to_person(data, person)

    def send_to_nearest(self, data):
        min_proximity = float(self.get_state(self.args["persons"][0]["proximity_id"]))
        for person in self.args["persons"]:
            person_proximity = float(self.get_state(person["proximity_id"]))
            if person_proximity <= min_proximity:
                min_proximity = person_proximity

        for person in self.args["persons"]:
            person_proximity = float(self.get_state(person["proximity_id"]))
            if person_proximity <= min_proximity + self.args["proximity_threshold"]:
                self.send_to_person(data, person)
    
    def send_when_present(self, data):
        if self.get_state(self.args["number_person"]) == "2":
            self.send_to_present(data)
        elif self.get_state(self.args["number_person"]) == "1":
            self.send_to_present(data)
            self.log("Staging notification for when home becomes occupied ...")
            self.staged_notifications_2.append(data)
        else:
            self.log("Staging notification for when home becomes occupied ...")
            self.staged_notifications_1.append(data)
    
    def callback_home_occupied_2(self, entity, attribute, old, new, kwargs):
        if len(self.staged_notifications_2) >= 1:
            self.log("Home is occupied by 2 ... Sending stagged notifications now ...")
        while len(self.staged_notifications_2) >= 1:
            current_data = self.staged_notifications_2.pop(0)
            self.send_to_present(current_data)
    
    def callback_home_occupied_1(self, entity, attribute, old, new, kwargs):
        if len(self.staged_notifications_1) >= 1:
            self.log("Home is occupied by 1 ... Sending stagged notifications now ...")
        while len(self.staged_notifications_1) >= 1:
            current_data = self.staged_notifications_1.pop(0)
            self.send_to_present(current_data)

    def callback_home_unoccupied(self, entity, attribute, old, new, kwargs):
        if len(self.staged_notifications_2) >= 1:
            self.log("Home is unoccupied ... Copying stagged notifications now ...")
            self.staged_notifications_1 = self.staged_notifications_2.copy()
            self.staged_notifications_2.clear()`

**Comment by swann05** [comment]
J'ai partiellement résolu mon problème par l'ajout d'une deuxième liste qui conserve la notification pour la seconde personne.
Si la 1ère personne effectue l'action, elle enlève la notif et ça `clear` la liste pour la seconde personne.
J'ai également ajouté un callback si on repart sans avoir vu la notif. Grace à la liste 2 qui est en attente pour la seconde personne, je la recopie sur la première et ça repart pour un tour.
Mon seul problème c'est que l'action `clear` vide toute la liste, j'aurais aimé cibler une notification de la liste seulement.

Ce n'est pas forcément très académique, je n'y connais rien en code ...

**Comment by swann05** [comment]
def cancel_staged_notifications_2(self, tag):
        self.log("Removing NOTIF with tag " + tag + " (if any) ...")
        for notification in list(self.staged_notifications_2):
            if notification["tag"] == tag:
                self.staged_notifications_2.remove(notification)

J'ai ajouté ça et modifié la ligne :
`self.staged_notifications_2.clear()` en `self.cancel_staged_notifications_2(tag)`

A priori ça marche ...
En utilisant
```
until : 
   - entity_id: zone.home 
     newstate: 0
```
dans chaque notif when_present ça permet également de faire disparaitre automatiquement la notif si on repart de la maison sans l'avoir discard. Et elle revient automatiquement au retour avec mon système de double liste.

**Comment by jlpouffier** [comment]
Effectivement, pour le moment le but de when_present c'est bien d'attendre avant d'envoyer la notification.
Si tu arrive a la maison et que la notification part, alors le NOTIFIER a fini son "job" et ta compagne ne recevra pas de notification a son tour.

Si tu souhaite modifier le notifier de ton coté, fait toi plaisir, je peux meme t'aider si tu as des question particuliere. Mais je ne souhaite pas modifier ce comportent de mon coté ;) 

JLo !

**Comment by swann05** [comment]
Sans problème, je suis content de ma modification ça marche impeccable.
Le seul point qui me pose problème pour une question de logique c'est le until zone.home à 0 avec mon callback unoccupied à 0. C'est le même trigger et les actions sont censés se produire en même temps et si until se produit avant le callback mon système perd de son intérêt. Mais pour l'instant ça se produit dans l'ordre callback puis until.. Coup de chance ?

**Comment by jlpouffier** [comment]
Je vais essayer de regarder ton code des que j’ai un peu de temps ;)
